### ISSUE TITLE
AnimmexClient.GetDirectVideoLinks() throws exception when 404 stream not found

### ISSUE THREAD

**Issue by rohitr97** [kade-robertson/AnimmexAPI#1]
AnimmexClient.GetDirectVideoLinks() results in System.Net.Http.HttpRequestException when a stream's URL is Not Found (404).

Example:
```
var api = new AnimmexClient();
var video = await api.ImFeelingLucky("outcast s01e01");
var links = await api.GetDirectLinks(video);
```
should result in the exception being thrown.

**Comment by kade-robertson** [comment]
Fixed with https://github.com/kade-robertson/AnimmexAPI/commit/f7dafe66754008e32f33e9be81045678bc84871e. :smile:
